[package]
name = "keycode"
version = "0.1.0"
edition = "2024"

[dependencies]
enigo = "0.5.0"
rdev = "0.5.3"
serde = { version = "1.0.219", features = ["derive"] }
strum = "0.27.2"
strum_macros = "0.27.2"